---
title: "bash pipeline"
subtitle: "_Tomato TET3 BS-seq selected plants_"
author: "Javier Antúnez Sánchez"
date: "`r format(Sys.time(), '%B %Y')`"
output:
  html_notebook:
    theme: darkly
    highlight: pygments
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
    code_folding: "none"
---

```{r setup, include=FALSE}
## Global options
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

bash variables
```{bash}
dir="/path/to/project/bsseq_selected" # double quotes important
genome="/path/to/genome/v4_Mt_Pt_TET3/S_lycopersicum_chromosomes.4.00_Mt_Pt_TET3.fa"
```


# 0. Get data

Place yourself in folder (name of your choice). You will need to run it again if you close the terminal
```{bash}
dir="/path/to/project/bsseq_selected" # double quotes important
mkdir $dir
```

Make directories for analysis
```{bash}
cd $dir
mkdir data data/1_raw data/2_trimmed data/3_mapped
mkdir qa     qa/1_raw   qa/2_trimmed   qa/3_mapped
```

get data from `Shared210`
```{bash}
cp -vr /path/to/data/2018_04_16_Tomato_high_coverage/*.fastq.gz $dir/data/1_raw 
```

The fastq files are paired end (150 cycles + 150 cycles)

Rename the files (create 2 vectors, original names and new names)
```{bash}
old_names=(JE1 JE2 JE5 JE6 JE7 JE8)
new_names=(wt_1 wt_2 a4_1 a4_2 a17_1 a17_2)

cd $dir/data/1_raw
for ((i=0; i<${#old_names[@]}; i++)); do
  mv ${old_names[$i]}.R1.RUN0094.L1.fastq.gz ${new_names[$i]}.R1.fq.gz &&
  mv ${old_names[$i]}.R2.RUN0094.L1.fastq.gz ${new_names[$i]}.R2.fq.gz
done
```

# 1. Quality control with [FastQC](https://www.bioinformatics.babraham.ac.uk/projects/fastqc/)

The quality of the sequencing data was first checked with FastQC.
```{bash}
cd $dir
fastqc -t 16 --quiet -o qa/1_raw/ data/1_raw/*
# aggregate results in one file
multiqc --filename qa/1_raw/01_raw_FastQC_multiqc qa/1_raw
```

# 2. Trim with [Fastp](https://github.com/OpenGene/fastp#fastp)

Trimming was performed with `fastp` with parameters `--cut_right --cut_window_size 4 --cut_mean_quality 20 --length_required 40 --overrepresentation_analysis`.
```{bash}
cd $dir/data/1_raw
for i in *.R1.fq.gz; do
  fastp --thread 16 --cut_right --cut_window_size 4 --cut_mean_quality 20 --length_required 40 \
    --overrepresentation_analysis \
    -i $i -I ${i/.R1./.R2.} \
    -o       ../2_trimmed/${i/.R1./.R1.trimmed.} -O      ../2_trimmed/${i/.R1./.R2.trimmed.} \
    -h ../../qa/2_trimmed/${i%.R1.*}_fastp.html -j ../../qa/2_trimmed/${i%.R1.*}_fastp.json ;
done
wait
# Multiqc reports of fastp
cd $dir
multiqc --filename qa/2_trimmed/02_trimmed_fastp_multiqc qa/2_trimmed
```

fastQC after trimming
```{bash}
cd $dir
fastqc -t 16 --quiet -o qa/2_trimmed/ data/2_trimmed/*
# aggregate results in one file
multiqc --filename qa/2_trimmed/02_trimmed_FastQC_multiqc qa/2_trimmed
```

# 3. Mapping with [Bismark](https://github.com/FelixKrueger/Bismark/tree/master/Docs)

Before mapping or indexing, I add the transgene to the sequence and the gtf following Alex's example from HCPro. I explained this in the Tomato genome preparation Markdown.

Set variable to fasta
```{bash}
genome="/path/to/genome/v4_Mt_Pt_TET3/S_lycopersicum_chromosomes.4.00_Mt_Pt_TET3.fa"
```

Mapping could also be done with BWA-meth followed by Methylscore for methylation extraction and DMR calling. I explain that method in another report.

Mapping with Bismark could followed by some other tool like [MethylDackel](https://github.com/dpryan79/MethylDackel), but I favou using the Bismark methylation extractor for consistency and then computing DMRs with DMRcaller in R.

Steps:
- bismark_genome_preparation
- bismark
- deduplicate_bismark
- bismark_methylation_extractor
- and then DMRcaller in R

## 3.1 Genome preparation

Index the reference for Bismark first (if it is not present already)
```{bash}
if [ ! -d $(dirname $genome)/Bisulfite_Genome ]; then
  bismark_genome_preparation --verbose $(dirname $genome)
fi
```

## 3.2. Mapping

And then run the mapping, I did and experiment with CRAM format, but it is complex. Use `--multicore 4`, drop this to use basename (both options don't work together)

```{bash}
cd $dir/data/2_trimmed
time_file="../timing_mapping_bismark.tsv"
printf "sample\tstart\tend\n" > $time_file
for i in *.R1.trimmed.fq.gz; do
  printf "$i\t$(date '+%Y/%m/%d %H:%M:%S')\t" >> $time_file &&
  bismark --multicore 4 --genome $(dirname $genome) -1 $i -2 ${i/.R1./.R2.} -o ../3_mapped &&
  printf "$(date '+%Y/%m/%d %H:%M:%S')\n" >> $time_file ;
done # 43 h without wt_1 # 12 h in parallel
```

Some stats for one sample (first test April 2018)
```
Secuential without multicore 
  26 Apr 14:23:39 - 27 Apr 19:49:37
  9.8 GB in 2 files
  66M reads paired end
  1d 5h 25m 57s (29.43h) to map the reads
  speed: 0.33 GB/h or 3 h/GB (both files)
  quickness: 2.2M reads/h or 27 min/M reads

Final Cytosine Methylation Report (sample 1 - wt3_1)
  C methylated in CpG context:	76.4%
  C methylated in CHG context:	50.0%
  C methylated in CHH context:	12.2%
```

### Improving mapping 

Changing the maximum insert size from the default 500 to 700 (we tried in 2018 with Julia, IT DIDNT IMPROVE THE MAPPING EFFICIENCY)
```{bash}
cd /path/to/project/data/2_trimmed
bismark -X 700 --multicore 4 ../../../Tomato_genome -o ../3_mapped -1 5_T_1P.fastq.gz -2 5_T_2P.fastq.gz
```

## 3.3. Deduplication

Mapped reads were deduplicated using `deduplicate_bismark`.
```{bash}
cd $dir/data/3_mapped
time_file="../timing_deduplication_bismark.tsv"
printf "sample\tstart\tend\n" > $time_file
for i in *_bt2_pe.bam; do
  printf "$i\t$(date '+%Y/%m/%d %H:%M:%S')\t" >> $time_file &&
  deduplicate_bismark --paired --bam $i &&
  printf "$(date '+%Y/%m/%d %H:%M:%S')\n" >> $time_file ;
done # ?? h (way faster than mapping)
```

## 3.4. Methylation Extraction 

Make CX_reports with Bismark methylation extractor. Using `bismark_methylation_extractor` with parameters `--cytosine_report --CX` is really to run the following commands in one `bismark_methylation_extractor`, `bismark2bedGraph` & `coverage2cytosine`.
```{bash}
cd $dir/data/3_mapped
time_file="../timing_methylation_extraction_bismark.tsv"
printf "sample\tstart\tend\n" > $time_file
for i in *.deduplicated.bam; do   
  printf "$i\t$(date '+%Y/%m/%d %H:%M:%S')\t" >> $time_file &&   
  bismark_methylation_extractor --multicore 2 --paired-end --ignore_r2 2 --cytosine_report \
    --CX --gzip --genome_folder $(dirname $genome) $i 2> $i.methext.log &&
  rm C??_*O?_${i%.bam}.txt.gz ${i%.bam}.bedGraph.gz ${i%.bam}.bismark.cov.gz &&
  printf "$(date '+%Y/%m/%d %H:%M:%S')" >> $time_file ;
  printf "\n" >> $time_file ;
done # ? h
```

Sort the CX_reports, as each file has a different order of chromosomes. (Maybe make a feature request in Bismark github page to get them sorted already)
```{bash}
cd $dir/data/3_mapped
for i in *.CX_report.txt; do
  sort -k1,1V -k2,2n $i --parallel 8 > $i.sorted &&
  mv $i.sorted $i ;
done
```

## 3.5. Cleaning & Reports

Clean the filenames to remove `.R1.trimmed`
```{bash}
cd $dir/data/3_mapped
for i in *.R1.trimmed*; do
  mv $i ${i/.R1.trimmed/}
done
```

Bismark reports
```{bash}
cd $dir/data/3_mapped
bismark2report
bismark2summary
```

Move CX_reports & clean the filenames
```{bash}
cd /path/to/project/$dir/data/3_mapped
mkdir ../4_methylation
for i in *.CX_report.txt*; do
  mv $i ../4_methylation/${i/_bismark_bt2_pe.deduplicated/}
done
```

Move qa reports to `qa`
```{bash}
cd $dir/data/3_mapped
mv *_report* ../../qa/3_mapped/
mv *M-bias*  ../../qa/3_mapped/
mv *.methext.log  ../../qa/3_mapped/
```
 
Multiqc reports of bismark
```{bash}
cd $dir/qa/3_mapped
multiqc --filename 03_mapped_bismark_multiqc .
```

Sorting and index for Samtools stats and later for BAMscale
```{bash}
cd $dir/data/3_mapped
for i in *.deduplicated.bam; do
  samtools sort -@40 -o ${i%.bam}.sorted.bam $i &&
  samtools index ${i%.bam}.sorted.bam ;
done
```

Samtools `flagstats` and `idxstats` and `stats`. Most of the results are meaningless, but the idxstats expected mapped reads per chromosome hints the chromosomal abnormality in chromosome 9.
```{bash}
cd $dir/data/3_mapped
mkdir ../../qa/3_mapped/samtools
for i in *sorted.bam; do
  (samtools flagstat $i > ../../qa/3_mapped/samtools/${i%.sorted.bam}.flagstats.txt && \
  samtools idxstats $i  > ../../qa/3_mapped/samtools/${i%.sorted.bam}.idxstats.txt && \
  samtools    stats $i  > ../../qa/3_mapped/samtools/${i%.sorted.bam}.stats.txt) ;
done
wait
# now condense reports with multiqc
cd ../../qa/3_mapped
multiqc --filename 03_mapped_samtools_multiqc samtools/
```

# 4. Generating tracks (bigwigs)

Make BigWigs of methylation (%mC)
```{bash}
cd $dir/data/4_methylation
mkdir ../5_tracks
for i in *.CX_report.txt; do
  CX_report2bigwig.sh -i $i -g ${genome/.fa/.chrom.sizes} -o ../5_tracks ;
done
```

Make BigWig of coverage from BAM files
```{bash}
cd $dir/data/3_mapped
for i in *.deduplicated.sorted.bam; do
  BAMscale scale -t 16 --binsize 10 --bam $i &&
  mv $i.scaled.bw ../5_tracks/${i/_bismark_bt2?(_pe).deduplicated.sorted.bam/.scaled.bw} ;   
  BAMscale scale -t 16 --scale no --operation unscaled --binsize 10 --bam $i &&   
  mv $i.unscaled.bw ../5_tracks/${i/_bismark_bt2?(_pe).deduplicated.sorted.bam/.coverage.bw} ;
done
```

# 5. Compute bin summary 

Generate 100 kbp bins of methylation data. The new script `CX_report2mC_bins.v1.0.pl` has constant header column names, including sample. You can now control the file name, throw output to STDOUT and set `--no_header` so you can concatenate several outputs into a long table. 
```{bash}
cd $dir/data/4_methylation
bins_file="tomato_tet3_selected.mC_bins.100kbp.tsv"
printf "chr\tstart\tend\tcontext\tmR\treads_m\treads_n\tsample\n" > $bins_file
for i in *.CX_report.txt; do
  CX_report2mC_bins.v1.0.pl -v --meth $i --bin 100000 --no_header -o - >> $bins_file
done
```

# 6. Merge replicas

For coverage purposes we want to merge the replicas to get one Bigwig per condition, but bad replica A4_1 needs to be discarded, so A4 will be just A4_2 

```{bash}
cd $dir/data/3_mapped 
# merge replicas for WT and A17
samtools merge -o wt.sorted.bam wt_1_bismark_bt2_pe.deduplicated.sorted.bam wt_2_bismark_bt2_pe.deduplicated.sorted.bam
samtools merge -o a17.sorted.bam a17_1_bismark_bt2_pe.deduplicated.sorted.bam a17_2_bismark_bt2_pe.deduplicated.sorted.bam  
# discard bad replica A4_1 (making A4 equal to A4_2)
cp a4_2_bismark_bt2_pe.deduplicated.sorted.bam a4.sorted.bam 
```

Make BigWig of coverage from merged BAM files
```{bash}
cd $dir/data/3_mapped
for i in {wt,a4,a17}.sorted.bam; do
  samtools index $i &&
  BAMscale scale -t 16 --scale no --operation unscaled --binsize 10 --bam $i &&   
  mv $i.unscaled.bw ../5_tracks/${i/.sorted.bam/.coverage.bw} ;
done
```

And then move all this tracks (methylation and coverage bigwigs of merged samples) to the jbrowse folder so they can be acceses from darvi.

# 7. Smooth bigwigs

After merging the CX_reports using DMRcaller functions and exporting them again to CX_report, I obtained the bigwig files using `CX_report2bigwig.sh`, but the files are too big to be easily loaded into R for the purpose of EnrichedHeatmaps. Therefire I want to make a low resolution bigwig using bins. I found this is possible with DeepTools bigwigcompare, which is designed to compare 2 bigwigs but you can give the same bigwig twice, and set a bin size for the output bigwig. It has an option to ignore empty regions `--skipNonCoveredRegions` (where the original bigwigs have no data) which is useful for DNA methylation data as we don't want to assume methylation is 0 just because there are no cytosines in a bin; however this option doesn't work at the moment.

```{bash}
cd $dir/data/5_tracks
for i in {wt,a4,a17}_{CG,CHG,CHH}.bw; do
  echo $i &&
  bigwigCompare --operation mean --binSize 50 -p max/2 -b1 $i -b2 $i -o ${i%.bw}_bins.bw
done
```





